"""The database schema is coherent and enforces its privacy commitments.

Runs against an in-memory SQLite database, so it needs no server. The point is
not to test SQLAlchemy - it is to assert the shape of the schema, particularly
the columns that deliberately do not exist.
"""

from __future__ import annotations

import pytest
from sqlalchemy import create_engine, inspect

from rto_sentinel.db.base import Base
from rto_sentinel.db.models import (
    Decision,
    ModelRun,
    OpsOverrideRecord,
    Order,
    OrderOutcomeRecord,
)

EXPECTED_TABLES = {"orders", "order_outcomes", "decisions", "ops_overrides", "model_runs"}


@pytest.fixture
def engine():
    engine = create_engine("sqlite+pysqlite:///:memory:", future=True)
    Base.metadata.create_all(engine)
    yield engine
    engine.dispose()


def test_all_tables_are_created(engine) -> None:
    assert set(inspect(engine).get_table_names()) == EXPECTED_TABLES


def test_orders_table_has_no_column_for_personal_identity() -> None:
    """SPEC section 09: identity fields hashed, PII never leaves the boundary.

    The strongest version of that promise is that the column does not exist. A
    nullable ``customer_name`` would eventually be populated by a well-meaning
    integration; a missing one cannot be.
    """
    columns = set(Order.__table__.columns.keys())
    forbidden = {
        "customer_name",
        "first_name",
        "last_name",
        "phone",
        "phone_number",
        "email",
        "gender",
        "age",
        "date_of_birth",
    }
    leaked = columns & forbidden
    assert not leaked, f"orders must not store personal identity: {leaked}"
    assert "customer_hash" in columns


def test_the_label_lives_in_its_own_table() -> None:
    """Separating the outcome from the order is what makes as-of joins natural.

    If ``outcome`` were a column on ``orders``, the convenient query would be the
    leaky one. Here the convenient query has to reference ``resolved_at``, and the
    time constraint becomes the obvious thing to write.
    """
    assert "outcome" not in Order.__table__.columns
    assert "is_rto" not in Order.__table__.columns
    assert "resolved_at" in OrderOutcomeRecord.__table__.columns
    assert "resolved_at" not in Order.__table__.columns


def test_decision_log_is_append_only_by_construction() -> None:
    """No ``updated_at``, and the repository exposes no update method.

    An audit trail that can be edited is not an audit trail. A changed decision
    is a new row.
    """
    assert "updated_at" not in Decision.__table__.columns

    from rto_sentinel.db.repositories import DecisionRepository

    methods = {name for name in dir(DecisionRepository) if not name.startswith("_")}
    assert not {"update", "update_decision", "delete", "modify"} & methods


def test_decision_row_carries_full_provenance() -> None:
    """A logged decision can be replayed against the engine that produced it."""
    columns = set(Decision.__table__.columns.keys())
    for required in ("engine_version", "model_name", "model_version", "config_fingerprint"):
        assert required in columns


def test_decision_constraints_encode_the_safeguards() -> None:
    """The appeal path and probability ranges are database-level guarantees."""
    constraint_names = {c.name for c in Decision.__table__.constraints if c.name}
    assert "ck_decisions_appeal_always_available" in constraint_names
    assert "ck_decisions_probability_is_a_probability" in constraint_names
    assert "ck_decisions_threshold_in_range" in constraint_names


def test_override_must_change_the_band() -> None:
    constraint_names = {c.name for c in OpsOverrideRecord.__table__.constraints if c.name}
    assert "ck_ops_overrides_override_changes_band" in constraint_names


def test_model_run_records_the_seal() -> None:
    """The "scored exactly once" seal is queryable, not just a file on a laptop."""
    columns = set(ModelRun.__table__.columns.keys())
    assert "test_set_scored" in columns
    assert "config_fingerprint" in columns
    assert "random_seed" in columns


def test_constraint_names_are_deterministic() -> None:
    """The naming convention makes Alembic migrations reviewable.

    Without it, constraint names are generated by the database and differ between
    engines, which turns every autogenerated migration into a diff nobody can
    read.
    """
    index_names = {index.name for index in Order.__table__.indexes}
    assert any(name and name.startswith("ix_") for name in index_names)
