"""add address_deliverability to simulation_latents

Revision ID: 27bd09cdc56a
Revises: 749598257b36
Create Date: 2026-08-28 02:10:13.809622
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "27bd09cdc56a"
down_revision: str | None = "749598257b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_latents", sa.Column("address_deliverability", sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_latents", "address_deliverability")
    # ### end Alembic commands ###
