"""initial schema

Revision ID: 749598257b36
Revises:
Create Date: 2026-08-28 01:23:30.392299
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "749598257b36"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_runs",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("generator_version", sa.String(length=16), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("n_customers", sa.Integer(), nullable=False),
        sa.Column("n_orders", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("realised_rto_rate_cod", sa.Float(), nullable=True),
        sa.Column("realised_rto_rate_prepaid", sa.Float(), nullable=True),
        sa.Column("realised_cod_share", sa.Float(), nullable=True),
        sa.Column("n_mature", sa.Integer(), nullable=False),
        sa.Column("n_immature", sa.Integer(), nullable=False),
        sa.Column("data_provenance", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "end_date >= start_date", name=op.f("ck_dataset_runs_run_dates_ordered")
        ),
        sa.CheckConstraint("n_orders > 0", name=op.f("ck_dataset_runs_run_has_orders")),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_dataset_runs")),
    )
    op.create_index(
        op.f("ix_dataset_runs_config_fingerprint"),
        "dataset_runs",
        ["config_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_runs_created_at"), "dataset_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_runs_generator_version"),
        "dataset_runs",
        ["generator_version"],
        unique=False,
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address_fingerprint", sa.String(length=32), nullable=False),
        sa.Column("address_line", sa.Text(), nullable=False),
        sa.Column("address_city", sa.String(length=128), nullable=False),
        sa.Column("address_state", sa.String(length=128), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column("pincode_tier", sa.String(length=16), nullable=False),
        sa.Column("addr_token_count", sa.Integer(), nullable=False),
        sa.Column("addr_has_house_number", sa.Boolean(), nullable=False),
        sa.Column("addr_has_floor_number", sa.Boolean(), nullable=False),
        sa.Column("addr_has_landmark", sa.Boolean(), nullable=False),
        sa.Column("addr_pincode_city_consistent", sa.Boolean(), nullable=False),
        sa.Column("addr_allcaps_ratio", sa.Float(), nullable=False),
        sa.Column("addr_gibberish_ratio", sa.Float(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "addr_allcaps_ratio >= 0 AND addr_allcaps_ratio <= 1",
            name=op.f("ck_addresses_allcaps_ratio_in_range"),
        ),
        sa.CheckConstraint(
            "addr_gibberish_ratio >= 0 AND addr_gibberish_ratio <= 1",
            name=op.f("ck_addresses_gibberish_ratio_in_range"),
        ),
        sa.CheckConstraint(
            "addr_token_count >= 0", name=op.f("ck_addresses_token_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_addresses_dataset_run_id_dataset_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(
        op.f("ix_addresses_address_fingerprint"), "addresses", ["address_fingerprint"], unique=True
    )
    op.create_index(op.f("ix_addresses_created_at"), "addresses", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_addresses_dataset_run_id"), "addresses", ["dataset_run_id"], unique=False
    )
    op.create_index(op.f("ix_addresses_pincode"), "addresses", ["pincode"], unique=False)
    op.create_index(op.f("ix_addresses_pincode_tier"), "addresses", ["pincode_tier"], unique=False)
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_hash", sa.String(length=64), nullable=False),
        sa.Column("signup_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_pincode", sa.String(length=6), nullable=False),
        sa.Column("home_pincode_tier", sa.String(length=16), nullable=False),
        sa.Column("generated_order_count", sa.Integer(), nullable=False),
        sa.Column("dataset_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_customers_dataset_run_id_dataset_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_created_at"), "customers", ["created_at"], unique=False)
    op.create_index(op.f("ix_customers_customer_hash"), "customers", ["customer_hash"], unique=True)
    op.create_index(
        op.f("ix_customers_dataset_run_id"), "customers", ["dataset_run_id"], unique=False
    )
    op.create_index(op.f("ix_customers_home_pincode"), "customers", ["home_pincode"], unique=False)
    op.create_index(op.f("ix_customers_signup_at"), "customers", ["signup_at"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("rung_id", sa.Integer(), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("dataset_run_id", sa.String(length=32), nullable=True),
        sa.Column("n_train", sa.Integer(), nullable=False),
        sa.Column("n_validation", sa.Integer(), nullable=False),
        sa.Column("n_test", sa.Integer(), nullable=False),
        sa.Column("test_set_scored", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_model_runs_dataset_run_id_dataset_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
        sa.UniqueConstraint("model_name", "model_version", name="model_version_unique"),
    )
    op.create_index(
        op.f("ix_model_runs_config_fingerprint"), "model_runs", ["config_fingerprint"], unique=False
    )
    op.create_index(op.f("ix_model_runs_created_at"), "model_runs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_model_runs_dataset_run_id"), "model_runs", ["dataset_run_id"], unique=False
    )
    op.create_index(op.f("ix_model_runs_run_id"), "model_runs", ["run_id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("customer_pk", sa.Integer(), nullable=False),
        sa.Column("customer_hash", sa.String(length=64), nullable=False),
        sa.Column("address_pk", sa.Integer(), nullable=False),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column("payment_method", sa.String(length=16), nullable=False),
        sa.Column("is_cod", sa.Boolean(), nullable=False),
        sa.Column("order_value_inr", sa.Float(), nullable=False),
        sa.Column("discount_inr", sa.Float(), nullable=False),
        sa.Column("discount_depth", sa.Float(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("cart_edited", sa.Boolean(), nullable=False),
        sa.Column("product_page_seconds", sa.Float(), nullable=True),
        sa.Column("sessions_before_purchase", sa.Integer(), nullable=True),
        sa.Column("device_class", sa.String(length=16), nullable=False),
        sa.Column("hour_of_day", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_late_night", sa.Boolean(), nullable=False),
        sa.Column("is_sale_day", sa.Boolean(), nullable=False),
        sa.Column("time_to_checkout_seconds", sa.Float(), nullable=True),
        sa.Column("cod_after_prepaid_failure", sa.Boolean(), nullable=False),
        sa.Column("courier_partner", sa.String(length=64), nullable=False),
        sa.Column("prior_order_count", sa.Integer(), nullable=False),
        sa.Column("prior_rto_count", sa.Integer(), nullable=False),
        sa.Column("prior_rto_rate", sa.Float(), nullable=True),
        sa.Column("days_since_last_order", sa.Float(), nullable=True),
        sa.Column("prepaid_to_cod_ratio", sa.Float(), nullable=True),
        sa.Column("mean_resolution_days", sa.Float(), nullable=True),
        sa.Column("is_new_customer", sa.Boolean(), nullable=False),
        sa.Column("split", sa.String(length=32), nullable=False),
        sa.Column("dataset_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("discount_inr >= 0", name=op.f("ck_orders_discount_non_negative")),
        sa.CheckConstraint(
            "dispatched_at IS NULL OR dispatched_at >= ordered_at",
            name=op.f("ck_orders_dispatch_after_order"),
        ),
        sa.CheckConstraint(
            "first_attempt_at IS NULL OR dispatched_at IS NULL OR first_attempt_at >= dispatched_at",
            name=op.f("ck_orders_attempt_after_dispatch"),
        ),
        sa.CheckConstraint(
            "hour_of_day >= 0 AND hour_of_day <= 23", name=op.f("ck_orders_hour_in_range")
        ),
        sa.CheckConstraint("item_count >= 1", name=op.f("ck_orders_item_count_at_least_one")),
        sa.CheckConstraint("order_value_inr > 0", name=op.f("ck_orders_order_value_positive")),
        sa.CheckConstraint(
            "prior_rto_count <= prior_order_count",
            name=op.f("ck_orders_prior_rtos_within_prior_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["address_pk"],
            ["addresses.id"],
            name=op.f("fk_orders_address_pk_addresses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_pk"],
            ["customers.id"],
            name=op.f("fk_orders_customer_pk_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_orders_dataset_run_id_dataset_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_address_pk"), "orders", ["address_pk"], unique=False)
    op.create_index(op.f("ix_orders_category"), "orders", ["category"], unique=False)
    op.create_index(op.f("ix_orders_courier_partner"), "orders", ["courier_partner"], unique=False)
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_customer_hash"), "orders", ["customer_hash"], unique=False)
    op.create_index(
        "ix_orders_customer_ordered_at", "orders", ["customer_hash", "ordered_at"], unique=False
    )
    op.create_index(op.f("ix_orders_customer_pk"), "orders", ["customer_pk"], unique=False)
    op.create_index(op.f("ix_orders_dataset_run_id"), "orders", ["dataset_run_id"], unique=False)
    op.create_index(op.f("ix_orders_day_index"), "orders", ["day_index"], unique=False)
    op.create_index(op.f("ix_orders_is_cod"), "orders", ["is_cod"], unique=False)
    op.create_index(op.f("ix_orders_merchant_id"), "orders", ["merchant_id"], unique=False)
    op.create_index(
        "ix_orders_merchant_ordered_at", "orders", ["merchant_id", "ordered_at"], unique=False
    )
    op.create_index(op.f("ix_orders_order_id"), "orders", ["order_id"], unique=True)
    op.create_index(op.f("ix_orders_ordered_at"), "orders", ["ordered_at"], unique=False)
    op.create_index(op.f("ix_orders_payment_method"), "orders", ["payment_method"], unique=False)
    op.create_index(op.f("ix_orders_split"), "orders", ["split"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_pk", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("reason_codes", sa.Text(), nullable=False),
        sa.Column("expected_value_inr", sa.Float(), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("config_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("appeal_available", sa.Boolean(), nullable=False),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column("is_control_holdout", sa.Boolean(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("appeal_available", name=op.f("ck_decisions_appeal_always_available")),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1",
            name=op.f("ck_decisions_probability_is_a_probability"),
        ),
        sa.CheckConstraint(
            "threshold >= 0 AND threshold <= 1", name=op.f("ck_decisions_threshold_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["order_pk"],
            ["orders.id"],
            name=op.f("fk_decisions_order_pk_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index(op.f("ix_decisions_band"), "decisions", ["band"], unique=False)
    op.create_index(
        "ix_decisions_band_decided_at", "decisions", ["band", "decided_at"], unique=False
    )
    op.create_index(op.f("ix_decisions_created_at"), "decisions", ["created_at"], unique=False)
    op.create_index(op.f("ix_decisions_decided_at"), "decisions", ["decided_at"], unique=False)
    op.create_index(op.f("ix_decisions_flagged"), "decisions", ["flagged"], unique=False)
    op.create_index(op.f("ix_decisions_order_id"), "decisions", ["order_id"], unique=False)
    op.create_index(op.f("ix_decisions_order_pk"), "decisions", ["order_pk"], unique=False)
    op.create_table(
        "delivery_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_pk", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_delivery_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["order_pk"],
            ["orders.id"],
            name=op.f("fk_delivery_events_order_pk_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_events")),
        sa.UniqueConstraint("order_pk", "sequence", name="event_sequence_unique"),
    )
    op.create_index(
        op.f("ix_delivery_events_created_at"), "delivery_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_event_type"), "delivery_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_occurred_at"), "delivery_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_order_id"), "delivery_events", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_order_pk"), "delivery_events", ["order_pk"], unique=False
    )
    op.create_index(
        "ix_delivery_events_order_sequence",
        "delivery_events",
        ["order_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "order_outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_pk", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("is_rto", sa.Boolean(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maturity_days", sa.Float(), nullable=True),
        sa.Column("is_mature", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(is_mature AND is_rto IS NOT NULL) OR (NOT is_mature AND is_rto IS NULL)",
            name=op.f("ck_order_outcomes_label_matches_maturity"),
        ),
        sa.CheckConstraint(
            "maturity_days IS NULL OR maturity_days >= 0",
            name=op.f("ck_order_outcomes_maturity_days_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["order_pk"],
            ["orders.id"],
            name=op.f("fk_order_outcomes_order_pk_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_outcomes")),
        sa.UniqueConstraint("order_pk", name=op.f("uq_order_outcomes_order_pk")),
    )
    op.create_index(
        op.f("ix_order_outcomes_created_at"), "order_outcomes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_outcomes_is_mature"), "order_outcomes", ["is_mature"], unique=False
    )
    op.create_index(op.f("ix_order_outcomes_is_rto"), "order_outcomes", ["is_rto"], unique=False)
    op.create_index(
        op.f("ix_order_outcomes_order_id"), "order_outcomes", ["order_id"], unique=False
    )
    op.create_index(op.f("ix_order_outcomes_outcome"), "order_outcomes", ["outcome"], unique=False)
    op.create_index(
        op.f("ix_order_outcomes_resolved_at"), "order_outcomes", ["resolved_at"], unique=False
    )
    op.create_table(
        "simulation_latents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_pk", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("true_rto_probability", sa.Float(), nullable=False),
        sa.Column("latent_logit", sa.Float(), nullable=False),
        sa.Column("customer_reliability", sa.Float(), nullable=False),
        sa.Column("latent_address_quality", sa.Float(), nullable=False),
        sa.Column("pincode_effect", sa.Float(), nullable=False),
        sa.Column("label_flipped", sa.Boolean(), nullable=False),
        sa.Column("dataset_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "true_rto_probability >= 0 AND true_rto_probability <= 1",
            name=op.f("ck_simulation_latents_true_probability_is_a_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_simulation_latents_dataset_run_id_dataset_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_pk"],
            ["orders.id"],
            name=op.f("fk_simulation_latents_order_pk_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_latents")),
        sa.UniqueConstraint("order_pk", name=op.f("uq_simulation_latents_order_pk")),
    )
    op.create_index(
        op.f("ix_simulation_latents_created_at"), "simulation_latents", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_simulation_latents_dataset_run_id"),
        "simulation_latents",
        ["dataset_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_latents_order_id"), "simulation_latents", ["order_id"], unique=False
    )
    op.create_table(
        "ops_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_pk", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("original_band", sa.String(length=16), nullable=False),
        sa.Column("override_band", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("operator_id", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "original_band <> override_band", name=op.f("ck_ops_overrides_override_changes_band")
        ),
        sa.ForeignKeyConstraint(
            ["decision_pk"],
            ["decisions.id"],
            name=op.f("fk_ops_overrides_decision_pk_decisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ops_overrides")),
    )
    op.create_index(
        op.f("ix_ops_overrides_created_at"), "ops_overrides", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ops_overrides_decision_pk"), "ops_overrides", ["decision_pk"], unique=False
    )
    op.create_index(
        op.f("ix_ops_overrides_direction"), "ops_overrides", ["direction"], unique=False
    )
    op.create_index(op.f("ix_ops_overrides_order_id"), "ops_overrides", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ops_overrides_order_id"), table_name="ops_overrides")
    op.drop_index(op.f("ix_ops_overrides_direction"), table_name="ops_overrides")
    op.drop_index(op.f("ix_ops_overrides_decision_pk"), table_name="ops_overrides")
    op.drop_index(op.f("ix_ops_overrides_created_at"), table_name="ops_overrides")
    op.drop_table("ops_overrides")
    op.drop_index(op.f("ix_simulation_latents_order_id"), table_name="simulation_latents")
    op.drop_index(op.f("ix_simulation_latents_dataset_run_id"), table_name="simulation_latents")
    op.drop_index(op.f("ix_simulation_latents_created_at"), table_name="simulation_latents")
    op.drop_table("simulation_latents")
    op.drop_index(op.f("ix_order_outcomes_resolved_at"), table_name="order_outcomes")
    op.drop_index(op.f("ix_order_outcomes_outcome"), table_name="order_outcomes")
    op.drop_index(op.f("ix_order_outcomes_order_id"), table_name="order_outcomes")
    op.drop_index(op.f("ix_order_outcomes_is_rto"), table_name="order_outcomes")
    op.drop_index(op.f("ix_order_outcomes_is_mature"), table_name="order_outcomes")
    op.drop_index(op.f("ix_order_outcomes_created_at"), table_name="order_outcomes")
    op.drop_table("order_outcomes")
    op.drop_index("ix_delivery_events_order_sequence", table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_order_pk"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_order_id"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_occurred_at"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_event_type"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_created_at"), table_name="delivery_events")
    op.drop_table("delivery_events")
    op.drop_index(op.f("ix_decisions_order_pk"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_order_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_flagged"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_decided_at"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_created_at"), table_name="decisions")
    op.drop_index("ix_decisions_band_decided_at", table_name="decisions")
    op.drop_index(op.f("ix_decisions_band"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_orders_split"), table_name="orders")
    op.drop_index(op.f("ix_orders_payment_method"), table_name="orders")
    op.drop_index(op.f("ix_orders_ordered_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_id"), table_name="orders")
    op.drop_index("ix_orders_merchant_ordered_at", table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_is_cod"), table_name="orders")
    op.drop_index(op.f("ix_orders_day_index"), table_name="orders")
    op.drop_index(op.f("ix_orders_dataset_run_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_pk"), table_name="orders")
    op.drop_index("ix_orders_customer_ordered_at", table_name="orders")
    op.drop_index(op.f("ix_orders_customer_hash"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_courier_partner"), table_name="orders")
    op.drop_index(op.f("ix_orders_category"), table_name="orders")
    op.drop_index(op.f("ix_orders_address_pk"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_model_runs_run_id"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_dataset_run_id"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_created_at"), table_name="model_runs")
    op.drop_index(op.f("ix_model_runs_config_fingerprint"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_customers_signup_at"), table_name="customers")
    op.drop_index(op.f("ix_customers_home_pincode"), table_name="customers")
    op.drop_index(op.f("ix_customers_dataset_run_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_customer_hash"), table_name="customers")
    op.drop_index(op.f("ix_customers_created_at"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_addresses_pincode_tier"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_pincode"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_dataset_run_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_created_at"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_address_fingerprint"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_dataset_runs_generator_version"), table_name="dataset_runs")
    op.drop_index(op.f("ix_dataset_runs_created_at"), table_name="dataset_runs")
    op.drop_index(op.f("ix_dataset_runs_config_fingerprint"), table_name="dataset_runs")
    op.drop_table("dataset_runs")
    # ### end Alembic commands ###
